<?php

/**
 * Depends on PHPExcel librarie ('sites/all/libraries/PHPExcel')
 * 'Link' column (G and D) should containe only one file name, otherwise only the first will be added to text
 */

/**
 * Implementation of hook_menu().
 */
function custom_xlsx_import_menu() {
  $items['custom_xlsx_import'] = array(
    'title' => 'XLSX import',
    'description' => 'Import data from .xlsx files (for "How to.." category).',
    'page callback' => 'custom_xlsx_import_import_stuff',
    'access arguments' => array(0),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Import data
 */
function custom_xlsx_import_import_stuff() {
  $output = '';
  $input_file_name = 'sites/default/files/HowdoI.xlsx';
  
  // Taxonomy ID of Educational material › How to ..
  $taxonomy_id = array('305');
  
  if (!class_exists('PHPExcel')) {
    $path = function_exists('libraries_get_path') ? libraries_get_path('PHPExcel') : 'sites/all/libraries/PHPExcel';
    if (!include($path . '/PHPExcel/IOFactory.php')) {
       drupal_set_message(t("Can't get PHPExcel library"));
    }
    else {
      $obj_reader = new PHPExcel_Reader_Excel2007();
      $obj_PHPExcel = $obj_reader->load($input_file_name);
      $sheet_data = $obj_PHPExcel->getActiveSheet()->toArray(null,true,true,true);
      $text_started = false;

      foreach ($sheet_data as $k=>$row_data) {
        if($row_data['A'] == 'Titel')
          $text_started = true;
        elseif ($text_started && (!empty($row_data['E']) || !empty($row_data['B']))) {
          // it's a title
          if(!empty($row_data['E'])) {
            // it's a node body
            $body_en = $row_data['F'];

            //  insert link to file into body of the node
            if(!empty($row_data['G'])) {
              $link_pattern = '/\b[\p{L}_0-9]{2,20}\.[a-zA-Z]{3}\b/i';
              preg_match($link_pattern, $row_data['G'], $linkf_data);
              $f_ext = explode('.', $linkf_data[0], 2);
              if(!empty($linkf_data[0]) && !empty($f_ext[1])) {
                    $body_en .= '<br>
    <video width="300" height="225" preload="none" controls="controls">
    <source type="video/' . $f_ext[1] . '" src="/sites/default/files/big_files/Guides/800/' . $linkf_data[0] . '"></source>

    Your browser doesn\'t support video.

    <br></br>


    	Please download the file: 

    <a href="/sites/default/files/big_files/Guides/800/' . $linkf_data[0] . '"></a>

</video>';
              }
            }

            $node_en = new stdClass();
            //  Main Node Fields
            $node_en->name = $row_data['E'];
            $node_en->title = $node_en->name;
            $node_en->body = $body_en;
            $node_en->type = 'ifshelp';
            $node_en->created = time();
            $node_en->changed = $node_en->created;
            $node_en->promote = 0;
            $node_en->sticky = 0;
            $node_en->format = 2;
            $node_en->status = 1;
            $node_en->language = 'en';
            $node_en->taxonomy = $taxonomy_id; 

            if ($node_en = node_submit($node_en)) {
              $node_en->uid = 1;
              node_save($node_en);
              drupal_set_message(t("Node " . $node_en->title . " added correctly"));
            } 
            else {
              drupal_set_message(t("Node " . $node_en->title . " added incorrectly"), "error");
            }
          }//--end--if(!empty($row_data['E'])) {
          // It's a title
          if(!empty($row_data['B'])) {
            // Node body
            $body_de = $row_data['C'];

            //insert link to file into body of the node
            // It's a link
            if(!empty($row_data['D'])) {
              $link_pattern = '/\b[\p{L}_0-9]{2,20}\.[a-zA-Z]{3}\b/i';
              preg_match($link_pattern, $row_data['D'], $linkf_data);
              $f_ext = explode('.', $linkf_data[0], 2);
              if(!empty($linkf_data[0]) && !empty($f_ext[1])) {
                $body_de .= '<br>
    <video width="300" height="225" preload="none" controls="controls">
    <source type="video/' . $f_ext[1] . '" src="/sites/default/files/big_files/Guides/800/' . $linkf_data[0] . '"></source>

    Your browser doesn\'t support video.

    <br></br>


    	Please download the file: 

    <a href="/sites/default/files/big_files/Guides/800/' . $linkf_data[0] . '"></a>

</video>';

              }
            }
            
            $node_da = new stdClass();
            $node_da->name = $row_data['B'];
            $node_da->title = $node_da->name;
            $node_da->body = $body_de;
            $node_da->type = 'ifshelp';
            $node_da->created = time();
            $node_da->changed = $node_da->created;
            $node_da->promote = 0;
            $node_da->sticky = 0;
            $node_da->format = 2;
            $node_da->status = 1;
            $node_da->language = 'da';
            $node_da->taxonomy = $taxonomy_id;
            //translation
            $node_da->tnid = !empty($node_en->nid) ? $node_en->nid : 0;

            if ($node_da = node_submit($node_da)) {
              $node_da->uid = 1;
              node_save($node_da);
              if(!empty($node_en->nid)) {
                //translation
                $node_en->tnid = $node_da->nid;
                node_save($node_en);
              }
              drupal_set_message(t("Node ".$node_da->title." added correctly"));
            } 
            else {
              drupal_set_message(t("Node ".$node_da->title." added incorrectly"), "error");
            }
            unset($node_da);
          }//--end--if(!empty($row_data['B'])) {
          unset($node_en);
        }//--end--elseif ($text_started && (!empty($row_data['E']) || !empty($row_data['B'])))
      }//--end--foreach ($sheet_data as $k=>$row_data)
    }
  }
  return $output;
}
